config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'all_tweets' => 'tweets#all'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'home' => 'static_pages/home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :tweets
  resources :relationships

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :status, presence: true, length: {maximum: 140}
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  has_many :tweets
  has_many :active_relationships, class_name: "Relationship",
                                 foreign_key: "follower_id"
  has_many :passive_relationships, class_name: "Relationship",
                                 foreign_key: "followed_id"
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  validates :name, presence: true,
                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 7}

  def feed
    following_ids = "SELECT followed_id FROM relationships
                      WHERE follower_id = :user_id"
    Tweet.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      #login and do stuff
      log_in user
      redirect_to user
    else
      #ERROR ERROR ABORT
      flash.now[:danger] = 'Invaild email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def login
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :logged_in_user

  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      flash[:success] = "Palindrome added!"
      redirect_to root_path
    else
      @feed_items = []
      render 'welcome/index'
    end
  end

  private

    def tweet_params
      params.require(:tweet).permit(:status)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Twitter for Palindromes"
      redirect_to @user
    else
      render 'new'
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end
  

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if logged_in?
      @tweet = current_user.tweets.build
      @feed_items = current_user.feed
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
        <li> <%= link_to "All Tweets", all_tweets_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Profile", current_user %></li>
            <li><%=link_to "Log Out", logout_path, method:"delete"%></li>
          </ul>
        </li>
        <%else%>
          <li><%= link_to "Login", login_path %></li>
        <%end%>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterforpalindromes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navber-fixed-top navbar-inverse"
    <div class="container">
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", '#' %> </li>
          <li><%= link_to "Login", '#' %> </li>
        </ul>
      </nav>
    </div>
  </header>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |err_msg| %>
        <li><%= err_msg %></li>
        <% end %>
      </ul>
  </div>
<%end%>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="tweets">
    <%= render @feed_items %>
  </ol>
<%end%>

app/views/shared/_tweet_form.html.erb
<%= form_for(@tweet) do |t| %>
<%= render 'shared/error_messages', object: t.object %>
<div class="field">
  <%= t.text_area :status, placeholder: "Write your palindrome here..." %>
</div>
<%= t.submit "Post", class: "btn btn-primary"%>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%=current_user.name%></h1>
<span><%= link_to "View Profile", current_user%></span>

app/views/static_pages/home.html.erb
/* I'm not sure if I'm going to use this page */

<h2>Twitter for Palindromes</h2>
<p>
  The time is now: <%= Time.now %>
</p>

<%= link_to "Sign up now!", '#', class: "btn, btn-lg, btn-primary" %>


<table>
  <tr>
    <th>User</th>
    <th>Status</th>
  </tr>
<% User.all.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
  </tr>
  <%end%>
</table>

app/views/static_pages/login.html.erb
<p> This is the login page </p>

app/views/tweets/_tweet.html.erb
<li id="tweet-<%= tweet.id %>">
  <span class="user"><%= link_to tweet.user.name, tweet.user %></span>
  <span class="status"><%= tweet.status %></span>
</li>

app/views/tweets/all.html.erb
<h2>All Tweets</h2>

<table>
  <tr>
    <th>User</th>
    <th>Tweet</th>
  </tr>
  <% Tweet.all.each do |tweet| %>
  <tr>
    <td><%= tweet.user_id %></td>
    <td><%= tweet.status %></td>
  </tr>
  <%end%>
</table>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |r| %>
  <div><%= hidden_field_tag :followed_id, @user.id%></div>
  <%= r.submit "Follow", class: "btn btn-primary" %>
<%end%>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
        <p>Already Follow</p>
    <%else%>
      <%= render 'follow' %>
    <%end%>
  </div>
<%end%>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<p>Find me in app/views/users/new.html.erb</p>

<div class="row">
  <div class="col-md-6">
    <%= form_for(@user) do |u| %>
      <%= render 'shared/error_messages', object: u.object %>

      <%= u.label :name %>
      <%= u.text_field :name, class: 'form-control' %>

      <%= u.label :password %>
      <%= u.password_field :password, class: 'form-control' %>

      <%= u.label :password_confirmation, "Confirmation" %>
      <%= u.password_field :password_confirmation, class: 'form-control' %>

      <%= u.submit "Create Account", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.tweets.any? %>
    <h3> Tweets (<%= @user.tweets.count %>)</h3>
    <table>
      <tr>
        <th>Status</th>
        <th>Created</th>
      </tr>
      <% @user.tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.status %></td>
        <td><%= tweet.created_at %></td>
      </tr>
      <% end %>
    <%end%>
  </div>
</div>

app/views/welcome/index.html.erb
<h2>Twitter for Palindromes</h2>
<p>
  The time is now: <%= Time.now %>
</p>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/tweet_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>

<%else%>

<%= link_to "Sign up now!", signup_path, class: "btn, btn-lg, btn-primary" %>

<table>
  <tr>
    <th>ID</th>
    <th>Username</th>
  </tr>
<% User.all.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
  </tr>
  <%end%>
</table>

<%end%>